PRACTICAL_TDD_SOURCE_DIRECTORY = src
PRACTICAL_TDD_SOURCE_FILES =


PRACTICAL_TDD_OBJECT_FILES = $(patsubst $(PRACTICAL_TDD_SOURCE_DIRECTORY)/%.cpp, $(PRACTICAL_TDD_BUILD_DIRECTORY)/$(PRACTICAL_TDD_SOURCE_DIRECTORY)/%.o, $(PRACTICAL_TDD_SOURCE_FILES))
PRACTICAL_TDD_DEPENDENCY_FILES = $(patsubst %.o, %.d, $(PRACTICAL_TDD_OBJECT_FILES))

include $(PRACTICAL_TDD_SOURCE_DIRECTORY)/make.mk

PRACTICAL_TDD_EXECUTABLE = $(PRACTICAL_TDD_BINARY_DIRECTORY)/practical-tdd

PRACTICAL_TDD_SOURCE_INCLUDES = $(PRACTICAL_TDD_SOURCE_DIRECTORY) $(PRACTICAL_TDD_INCLUDE_DIRECTORY)

PRACTICAL_TDD_SOURCE_CPP_INCLUDE = $(patsubst %,-I%,$(PRACTICAL_TDD_SOURCE_INCLUDES))

practical-tdd: $(PRACTICAL_TDD_EXECUTABLE)
	$(PRACTICAL_TDD_EXECUTABLE)

$(PRACTICAL_TDD_EXECUTABLE): $(PRACTICAL_TDD_OBJECT_FILES)
	@$(MAKE_DIRECTORY) $(@D)
	$(CPP) -o $@ $^ $(PRACTICAL_TDD_SOURCE_CPP_INCLUDE)

$(PRACTICAL_TDD_BUILD_DIRECTORY)/src/%.o: $(PRACTICAL_TDD_SOURCE_DIRECTORY)/%.cpp $(PRACTICAL_TDD_BUILD_DIRECTORY)/src/%.d
	@$(MAKE_DIRECTORY) $(@D)
	$(CPP) -c -o $@ $< $(PRACTICAL_TDD_SOURCE_CPP_INCLUDE)

$(PRACTICAL_TDD_DEPENDENCY_FILES):

include $(wildcard $(PRACTICAL_TDD_DEPENDENCY_FILES))

.PHONY: practical-tdd

