PRACTICAL_TDD_TEST_DIRECTORY = test
PRACTICAL_TDD_TEST_FILES =

PRACTICAL_TDD_TEST_OBJECT_FILES = $(patsubst $(PRACTICAL_TDD_TEST_DIRECTORY)/%.cpp, $(PRACTICAL_TDD_BUILD_DIRECTORY)/$(PRACTICAL_TDD_TEST_DIRECTORY)/%.o, $(PRACTICAL_TDD_TEST_FILES))
PRACTICAL_TDD_TEST_DEPENDENCY_FILES = $(patsubst %.o, %.d, $(PRACTICAL_TDD_TEST_OBJECT_FILES))

include $(PRACTICAL_TDD_TEST_DIRECTORY)/make.mk

PRACTICAL_TDD_TEST_EXECUTABLE = $(PRACTICAL_TDD_BINARY_DIRECTORY)/practical-tdd-test
PRACTICAL_TDD_TEST_MAIN = $(PRACTICAL_TDD_TEST_DIRECTORY)/main.cpp

PRACTICAL_TDD_TEST_INCLUDES = $(PRACTICAL_TDD_SOURCE_INCLUDES) $(PRACTICAL_TDD_TEST_DIRECTORY) $(CBUNIT_INCLUDE_DIRECTORY)

PRACTICAL_TDD_TEST_CPP_INCLUDE = $(patsubst %,-I%,$(PRACTICAL_TDD_TEST_INCLUDES))

test: practical-tdd-test
practical-tdd-test: $(PRACTICAL_TDD_TEST_EXECUTABLE)
	$(PRACTICAL_TDD_TEST_EXECUTABLE) --reporter spec --output ansi256

$(PRACTICAL_TDD_TEST_EXECUTABLE): $(PRACTICAL_TDD_TEST_MAIN) $(PRACTICAL_TDD_OBJECT_FILES) $(PRACTICAL_TDD_TEST_OBJECT_FILES) $(CBUNIT_LIBRARY)
	@$(MAKE_DIRECTORY) $(@D)
	$(CPP) -o $@ $^ $(PRACTICAL_TDD_TEST_CPP_INCLUDE)

$(PRACTICAL_TDD_BUILD_DIRECTORY)/test/%.o: $(PRACTICAL_TDD_TEST_DIRECTORY)/%.cpp $(PRACTICAL_TDD_BUILD_DIRECTORY)/test/%.d
	@$(MAKE_DIRECTORY) $(@D)
	$(CPP) -c -o $@ $< $(PRACTICAL_TDD_TEST_CPP_INCLUDE)

$(PRACTICAL_TDD_TEST_DEPENDENCY_FILES):

include $(wildcard $(PRACTICAL_TDD_TEST_DEPENDENCY_FILES))

.PHONY: practical-tdd-test test